# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Ching-Tse Chen
description: >- # this means to ignore newlines until "baseurl:"
  Ching-Tse's website
baseurl: "/." # the subpath of the site
url: "https://hugh304123.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Research
    - name: Blog

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: chingtse.chen@chicagobooth.edu
      link: mailto:chingtse.chen@dchicagobooth.edu
    # - name: WeChat
    #   value: YourWeChatUsername
    #   link: "#"
  follow:
    # - name: Twitter
    #   link: http://twitter.com/YourTwitterUsername
    #   username: "@YourTwitterUsername"
    # - name: Facebook
    #   link: http://facebook.com/YourFacebookUsername
    - name: LinkedIn
      link: https://www.linkedin.com/in/ching-tse-chen-509aa8b1/
    # - name: GitHub
    #   link: http://github.com/YourGitHubUsername
    # - name: Dribbble
    #   link: https://dribbble.com/YourDribbbleUsername
    # - name: RSS
    #   link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
